### ISSUE TITLE
Remove doxygen from this repository

### ISSUE THREAD

**Issue by abitmore** [bitshares/dev.bitshares.works#132]
We created a new repository for doxygen (for better SEO): https://github.com/bitshares/doxygen.bitshares.org.

If the generated doxygen HTML is not directly hosted here, maybe we don't need to do anything.

**Comment by cedar-book** [comment]
[This page second section](https://dev.bitshares.works/en/master/api/namespaces.html) points new doxygen website.  Still need the output XML files to build API pages:  [Blockchain API(s)](https://dev.bitshares.works/en/master/api/blockchain_api.html) each API page and [Wallet API](https://dev.bitshares.works/en/master/api/wallet_api.html). And [this page first section](https://dev.bitshares.works/en/master/api/namespaces.html) pages.
