### ISSUE TITLE
doxygenenum: Cannot find enum in doxygen xml output for project “bitshares”

### ISSUE THREAD

**Issue by SemenMartynov** [bitshares/dev.bitshares.works#179]
Please, check this page, there are 2 warnings: https://dev.bitshares.works/en/master/api/objects_ids.html#definitions

Protocol Space (1.x.x)

`doxygenenum: Cannot find enum “graphene::chain::object_type” in doxygen xml output for project “bitshares” from directory: ../doxygen/xml/`

Implementation Space (2.x.x)

`doxygenenum: Cannot find enum “graphene::chain::impl_object_type” in doxygen xml output for project “bitshares” from directory: ../doxygen/xml/`

**Comment by abitmore** [comment]
The explicit definitions have been replaced with macros, I guess that's why Doxygen can no longer find them.

I don't know how to fix the docs to automatically generate the new list. BTW the "List of commonly used objects" on the same page is outdated already.

For more info, please search for `GRAPHENE_DEFINE_IDS` in https://github.com/bitshares/bitshares-core/blob/master/libraries/protocol/include/graphene/protocol/types.hpp and https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/types.hpp, pasted below (may be outdated when there is a new version released).
```
GRAPHENE_DEFINE_IDS(protocol, protocol_ids, /*protocol objects are not prefixed*/,
                    (null)
                    (base)
                    (account)
                    (asset)
                    (force_settlement)
                    (committee_member)
                    (witness)
                    (limit_order)
                    (call_order)
                    (custom) // unused
                    (proposal)
                    (operation_history)
                    (withdraw_permission)
                    (vesting_balance)
                    (worker)
                    (balance)
                    (htlc)
                    (custom_authority)
                    (ticket)
                    (liquidity_pool)
                   )
```

```
GRAPHENE_DEFINE_IDS(chain, implementation_ids, impl_,
                    (global_property)
                    (dynamic_global_property)
                    (reserved0)
                    (asset_dynamic_data)
                    (asset_bitasset_data)
                    (account_balance)
                    (account_statistics)
                    (transaction_history)
                    (block_summary)
                    (account_transaction_history)
                    (blinded_balance)
                    (chain_property)
                    (witness_schedule)
                    (budget_record)
                    (special_authority)
                    (buyback)
                    (fba_accumulator)
                    (collateral_bid))
```

**Comment by SemenMartynov** [comment]
Thanks.

Is there any way to get all objects' IDs?

It's all pretty clear with `types.hpp` but a bit difficult with `operations.hpp` since we are generating IDs dynamically (previously it was much more explicitly https://github.com/abitmore/bitshares-core/blob/170523826b82ba754eeae8706a891797b4b37ee8/libraries/chain/include/graphene/chain/protocol/operations.hpp#L50)

**Comment by abitmore** [comment]
I will add comments to operations.hpp and types.hpp (manually).

**Comment by abitmore** [comment]
Wish this would make it clearer: https://github.com/bitshares/bitshares-core/pull/2306. I still don't know how to automatically update https://dev.bitshares.works/en/master/api/objects_ids.html though.

**Comment by sschiessl-bcp** [comment]
Was that generation ever automated?

**Comment by abitmore** [comment]
The error message `Cannot find enum “graphene::chain::object_type” in doxygen xml output` means there were something on the page generated from the XML file, no matter what it was. The XML file was updated on every core release.

**Comment by SemenMartynov** [comment]
Thx!
